[theme]
primaryColor = "#262730"  # Dark gray for buttons and accents
backgroundColor = "#f5f5f5"  # Light gray background
secondaryBackgroundColor = "#e0e0e0"  # Slightly darker gray for secondary elements
textColor = "#262730"  # Dark gray for text
font = "sans serif"  # Clean, modern font